theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tracking
    - toc.integrate
    - toc.follow
   
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list

extra_css:
  - assets/css/people.css
  - assets/css/publication.css

extra_javascript:
  - assets/js/publication.js


site_name: PennState System Security Lab
site_url: https://ps3lab.github.io/
docs_dir: src
nav:
    - Home: index.md
    - People: people.md
    - Publications: generated/publications.md
    - Fundings: fundings.md
    - Contact: contact.md
