theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tracking

site_name: PennState System Security Lab
site_url: https://ps3lab.github.io/
docs_dir: src
nav:
    - Home: index.md
    - People: people.md
    - Publications: generated/publications.md
    - Fundings: fundings.md
    - Contact: contact.md
