theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.tracking

site_name: PSU Security Lab
site_url: http://tbd
docs_dir: src
nav:
    - Home: index.md
    - Publications: publications.md
    - Fundings: fundings.md
    - Contact: contact.md